language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

warnings_are_errors: true

services:
  - mysql

php:
  - "7.3.23"

before_install:
  - node -v
  - npm -v
  - node -p process.versions
  - node -p process.platform
  - node -p process.arch
  - npm install node-sass@latest

install:
  - composer self-update --2
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:migrations:migrate --no-interaction --env=test
  - php bin/console doctrine:fixtures:load --no-interaction --env=test

script:
  - ./vendor/bin/simple-phpunit --coverage-text --testdox-text phpunit-report/testdox
  - php phpunit-coverage-checker.php phpunit-report/coverage/clover.xml 70
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpstan analyse src tests
  - php bin/console lint:twig ./templates/
