language: php
php:
  - "7.3.23"

services:
  - mysql

before_script: phpenv config-add myconfig.ini

install:
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - ./vendor/bin/simple-phpunit --coverage-text --colors
