language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

warnings_are_errors: true

services:
  - mysql

php:
  - "7.3.23"

before_install:
  - nvm install node

install:
  - npm install -g npm@4
  - npm install
  - composer self-update --2
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:migrations:migrate --no-interaction --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

before_script:
  - npm run build

script:
  - ./vendor/bin/simple-phpunit --coverage-text --testdox-text phpunit-report/testdox
  - php phpunit-coverage-checker.php phpunit-report/coverage/clover.xml 70
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpstan analyse src tests
  - php bin/console lint:twig ./templates/
