language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/symfony-bridge/.phpunit

warnings_are_errors: true

services:
  - mysql

php:
  - "7.3.23"

install:
  - composer install --prefer-dist --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:migrations:migrate --no-interaction --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - ./vendor/bin/simple-phpunit --coverage-text
  - php phpunit-coverage-checker.php clover.xml 30
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpstan analyse src tests
  - php bin/console lint:twig ./templates/
