version: "3"
services:
  mariadb:
    image: mariadb:10.1
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_USER: "devuser"
      MYSQL_PASSWORD: "devpassword"
      MYSQL_DATABASE: "devdb"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:mysql
    ports:
      - 8001:80
    environment:
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
      MYSQL_ROOT_PASSWORD: rootpwd
      PMA_HOST: mysql

volumes:
  mariadb:
